# Week 8
## Classification
#### In-class practice excercise
Train a classifier to learn the rock types in core data

In [1]:
import matplotlib
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

Load data from XLSX file from a specific Sheet

In [2]:
c=pd.read_excel('Core_SM.xlsx',sheet_name='Data',index_col=0) # choose col 0 as index
c.head()

Porosity     TOC  Quartz  Calcite RockClass
Depth                                                
4644.985      6.67    4.15    38.6      0.0        SS
4647.085      6.07    4.25    48.6      6.2        SS
4649.185      4.91    3.40    41.0      2.5        SS
4651.285      6.00    0.39     4.6     66.4        LS
4653.490      5.63 -999.00    37.0      0.6        SS

make the depth column an index, it is a good practice

In [4]:
c.index.name='Depth' # name col 0 i.e. the index col. as Depth

In [9]:
# Investigate the unique items in rock class column
c['RockClass'].unique()

array(['SS', 'LS', 'DO'], dtype=object)

In [7]:
# Do statistical description of the dataframe... 
c.describe()

# why is Class Missing? 
# look at min...and mean
# look at the count
    
# What are you obeservations ?

Porosity         TOC      Quartz     Calcite
count  157.000000  167.000000  167.000000  167.000000
mean     4.288153  -56.233473   27.963473   12.122156
std      1.372243  238.653729   13.875863   19.819573
min      0.880000 -999.000000    0.000000    0.000000
25%      3.420000    2.455000   17.450000    0.000000
50%      4.380000    3.720000   29.700000    2.400000
75%      5.230000    4.915000   38.300000   12.700000
max      8.050000    7.480000   59.400000   78.600000

###### Missing Data is Dangerous 

#### Check Missing Values

In [8]:
c.isna().any() #check if NaN are present
                # why no nans detected in TOC column?
                # only np.nan can be detected

Porosity      True
TOC          False
Quartz       False
Calcite      False
RockClass    False
dtype: bool

In [10]:
# At what depth Porosity is NaN ?

c[np.isnan(c["Porosity"])==True].index

Float64Index([4665.985000000001, 4704.310000000001, 4753.450000000001,
              4773.190000000001, 4873.360000000001, 4936.254999999999,
              4938.565000000001,           4978.57,           5012.17,
                       5014.375],
             dtype='float64', name='Depth')

In [11]:
# provide a list of items that should be considered as missing.
# using inplace to save the replacement of various missing values.

c.replace([np.inf, -np.inf, np.inf, -999, 999, '', " ", 'inf', 'NaN'], np.nan, inplace=True)

In [12]:
c.isna().any() #check if NaN are present

Porosity      True
TOC           True
Quartz       False
Calcite      False
RockClass    False
dtype: bool

In [ ]:
c.iloc[:,:4].values

#### Do not Remove Missing Data

In [10]:
# it is not a good idea to drop a column or a row

from sklearn.impute import SimpleImputer 
# imputer looks all columns, finds cells with missing value, and replaces median for the missing value

imp = SimpleImputer(missing_values=np.nan,strategy='median')

imp.fit(c.iloc[:,:4].values) # understand statistics of the train data

a_imp = imp.transform(c.iloc[:,:4].values) # no missing values here

c.iloc[:,:4]=a_imp

MEAN: Suitable for continuous data without outliers


SimpleImputer can be useful in cases where the number of missing observations is low. However, for large number of missing values, using mean or median can result in loss of variation in data and it is better to use imputations. 

In [11]:
# Do another statistical description of the dataframe after fixing the missing vlaues problem.
# look at min...and mean
# look at the count    

In [12]:
#check if NaN are present

In [13]:
# find the depths for which the porosity is greater than 6 and RockClass is Sandstone

In [14]:
# masking and slicing

# obtain a slice of data for which the porosity is greater than 6 and RockClass is Sandstone

### Multi-Label Classification

The data now contains only useful features, but they are not in a format that the machine learning algorithms can understand. We need to transform the strings "SS", "LS" and "DO" into numeric/binary variables that indicate the rock class.

#### One-hot encoding

###### Method 1: We can do that using the pandas get_dummies function on the whole dataframe

In [15]:
c_mlabel = pd.get_dummies(c)

# looks at columns that are categorical and creates a new column for each new category

#  we give each category its own dimension

In [16]:
c_mlabel

Porosity   TOC  Quartz  Calcite  RockClass_DO  RockClass_LS  \
Depth                                                                   
4644.985      6.67  4.15    38.6      0.0             0             0   
4647.085      6.07  4.25    48.6      6.2             0             0   
4649.185      4.91  3.40    41.0      2.5             0             0   
4651.285      6.00  0.39     4.6     66.4             0             1   
4653.490      5.63  3.91    37.0      0.6             0             0   
...            ...   ...     ...      ...           ...           ...   
5003.455      3.77  3.91    26.7     15.4             1             0   
5004.715      4.60  3.52    31.0      0.0             1             0   
5010.490      4.16  2.47    16.0      8.7             1             0   
5012.170      4.38  2.32    24.8     19.8             1             0   
5014.375      4.38  3.66    20.2     11.9             1             0   

          RockClass_SS  
Depth                   
4644.985             1  
4647.085             1  
4649.185             1  
4651.285             0  
4653.490             1  
...                ...  
5003.455             0  
5004.715             0  
5010.490             0  
5012.170             0  
5014.375             0  

[167 rows x 7 columns]

###### Method 2: We can do that using the pandas get_dummies on a specific column

In [17]:
c = pd.get_dummies(c, columns=['RockClass']) # using label name
c.head()

Porosity   TOC  Quartz  Calcite  RockClass_DO  RockClass_LS  \
Depth                                                                   
4644.985      6.67  4.15    38.6      0.0             0             0   
4647.085      6.07  4.25    48.6      6.2             0             0   
4649.185      4.91  3.40    41.0      2.5             0             0   
4651.285      6.00  0.39     4.6     66.4             0             1   
4653.490      5.63  3.91    37.0      0.6             0             0   

          RockClass_SS  
Depth                   
4644.985             1  
4647.085             1  
4649.185             1  
4651.285             0  
4653.490             1

###### Method 3: We can do that using the sklearn onehotencder

In [18]:
c_mlabel.isna().any() #check if NaN are present

Porosity        False
TOC             False
Quartz          False
Calcite         False
RockClass_DO    False
RockClass_LS    False
RockClass_SS    False
dtype: bool

## Supervised Learning - Classification


### Train a machine learning model (classifier) to classify a rock as Dolomite or Not-Dolomite based on porosity, quartz, calcite, and TOC 

### Define features

In [19]:
X = c.iloc[:,:4].values # features

X  

array([[ 6.67,  4.15, 38.6 ,  0.  ],
       [ 6.07,  4.25, 48.6 ,  6.2 ],
       [ 4.91,  3.4 , 41.  ,  2.5 ],
       [ 6.  ,  0.39,  4.6 , 66.4 ],
       [ 5.63,  3.91, 37.  ,  0.6 ],
       [ 5.85,  3.91, 40.6 ,  2.7 ],
       [ 0.88,  3.5 , 29.3 ,  5.5 ],
       [ 6.14,  4.12, 43.1 , 10.  ],
       [ 5.27,  3.61, 33.7 , 21.9 ],
       [ 6.02,  5.92, 54.8 ,  0.  ],
       [ 4.38,  3.15, 50.  ,  7.  ],
       [ 5.27,  4.68, 42.1 , 11.5 ],
       [ 4.42,  2.49, 27.3 , 21.1 ],
       [ 5.55,  3.91, 35.6 , 25.3 ],
       [ 5.09,  3.49, 40.9 ,  0.4 ],
       [ 2.52,  2.5 , 20.4 , 31.  ],
       [ 2.7 ,  1.51,  3.7 , 28.5 ],
       [ 2.77,  3.91, 11.1 , 36.8 ],
       [ 2.09,  0.83,  6.8 , 61.3 ],
       [ 1.96,  1.14, 10.6 , 45.8 ],
       [ 2.13,  1.29, 10.3 , 53.4 ],
       [ 2.74,  1.44,  8.4 , 56.7 ],
       [ 2.03,  0.49,  1.8 , 68.8 ],
       [ 2.16,  0.64,  0.  , 78.6 ],
       [ 2.65,  0.8 ,  4.3 , 74.  ],
       [ 2.34,  0.92,  6.4 , 56.8 ],
       [ 1.79,  0.53,  0.  , 67.4 ],
 

In [20]:
X.shape # 4 features

(167, 4)

In [23]:
y_DS = c_mlabel.iloc[:,4].values
y_DS.shape
# Not Dol, Yes Dol
y_DS # label.... Not Dol , Yes Dol

array([0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1], dtype=uint8)

In [24]:
np.bincount(y_DS)   # Not Dol, Yes Dol

array([82, 85], dtype=int64)

In [25]:
from sklearn.model_selection import train_test_split
X_tr, X_ts, y_tr_DS, y_ts_DS = train_test_split(X, y_DS, stratify=y_DS)

In [26]:
from sklearn.linear_model import LogisticRegression
lr1 = LogisticRegression().fit(X_tr, y_tr_DS)
print("logistic regression test score: %f" % lr1.score(X_ts, y_ts_DS))
print("logistic regression train score: %f" % lr1.score(X_tr, y_tr_DS))

from sklearn.neighbors import KNeighborsClassifier
kn1 = KNeighborsClassifier().fit(X_tr, y_tr_DS)
print("knn classifier test score: %f" % kn1.score(X_ts, y_ts_DS))
print("knn classifier train score: %f" % kn1.score(X_tr, y_tr_DS))

from sklearn.svm import SVC
svc1 = SVC(kernel='poly', C=1, gamma=0.1, random_state=0).fit(X_tr, y_tr_DS)
print("support vector test score: %f" % svc1.score(X_ts, y_ts_DS))
print("support vector train score: %f" % svc1.score(X_tr, y_tr_DS))

from sklearn.ensemble import RandomForestClassifier
rf1 = RandomForestClassifier(n_estimators=200, max_depth=4, random_state=0).fit(X_tr, y_tr_DS)
print("random forest test score: %f" % rf1.score(X_ts, y_ts_DS))
print("random forest train score: %f" % rf1.score(X_tr, y_tr_DS))

## number of trees around 100 to 500 are suitable for simple cases

logistic regression test score: 0.857143
logistic regression train score: 0.848000
knn classifier test score: 0.833333
knn classifier train score: 0.920000
support vector test score: 1.000000
support vector train score: 1.000000
random forest test score: 0.928571
random forest train score: 1.000000


#### Do the same excerices to predict Limestone or No Limestone?

In [27]:
## y_LS = 

support vector test score: 1.000000
support vector train score: 1.000000


# Multiclass Classification
### Random Forest


In [31]:
y_rf = c_mlabel.iloc[:,4:].values
y_rf

array([[0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [0, 1, 0],
       [0, 0, 1],
       [0, 0, 1],
       [1, 0, 0],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [1, 0, 0],
       [0, 0, 1],
       [0, 0, 1],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 1, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 0, 1],
       [1, 0, 0],
       [0, 0, 1],
       [0, 0, 1],
       [1, 0, 0],
       [0, 0, 1],
       [1, 0, 0],
       [0, 0, 1],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0,

In [32]:
# split the data into train-test dataset 

from sklearn.model_selection import train_test_split
X_tr, X_ts, y_tr, y_ts = train_test_split(X, y_rf, stratify=y_rf)


# can other proprtion be used? 
# what is random state?

In [33]:
from sklearn.ensemble import RandomForestClassifier
rf1 = RandomForestClassifier(n_estimators=200, max_depth=4, random_state=0).fit(X_tr, y_tr)
print("random forest test score: %f" % rf1.score(X_ts, y_ts))
print("random forest train score: %f" % rf1.score(X_tr, y_tr))

random forest test score: 0.952381
random forest train score: 0.992000


In [34]:
import random
random.sample(range(1, 20), 6)

[13, 2, 6, 12, 1, 3]

In [35]:
# Due to the lack of core measurement, we randomly select three rows from test data

import random

a = random.sample(range(1, 20), 6)

X_new = X_ts[a,:]
X_new

array([[ 5.22,  4.69, 33.7 ,  0.7 ],
       [ 5.19,  2.9 , 42.8 ,  0.  ],
       [ 4.4 ,  2.64, 23.2 ,  2.4 ],
       [ 4.38,  5.07, 19.1 ,  0.  ],
       [ 6.37,  4.99, 43.4 ,  1.8 ],
       [ 3.77,  5.71, 37.9 ,  0.  ]])

#####  Use Knn for Multiclass Classification

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
kn=KNeighborsClassifier